apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          imagePullPolicy: Always
          image: gcr.io/gorgias-magic-777/gorgias-magic:latest
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          env:
            - name: POSTGRES_SERVICE_HOST
              value: postgres.default.svc.cluster.local
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: user
            - name: POSTGRES_DB_PSWD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
            - name: POSTGRES_DB_NAME
              value: postgres
          ports:
            - containerPort: 5000
