apiVersion: v1
kind: Service
metadata:
  name: gorgias-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: tcp-5000