apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          imagePullPolicy: Always
          image: gcr.io/gorgias-magic-777/gorgias-magic:latest
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          env:
            - name: SERVICE_POSTGRES_SERVICE_HOST
              value: service-postgres.default.svc.cluster.local
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: user
            - name: POSTGRES_DB_PSWD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 5