kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-main-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
    
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-replica-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
    
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-main-pv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"    

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-replica-pv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"