apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-faster
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv   
  labels:
    type: gcePersistentDisk
    app: postgres
spec:
  storageClassName: ssd-faster
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: gorgias-postgres-0
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: postgres-disk
    fsType: xfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-replica-pv   
  labels:
    type: gcePersistentDisk
    app: postgres
spec:
  storageClassName: ssd-faster
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: gorgias-postgres-replica-0
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: postgres-replica-disk
    fsType: xfs
