apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres

spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
    
---

apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  labels:
    app: postgres-replica

spec:
  type: ClusterIP
  ports:
  - name: postgres-replica
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-replica
    
---