apiVersion: v1
kind: Service
metadata:
  name: postgres-main
  labels:
    app: postgres-main

spec:
  type: ClusterIP
  ports:
  - name: postgres-main
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-main
    
---

apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  labels:
    app: postgres-replica

spec:
  type: ClusterIP
  ports:
  - name: postgres-replica
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-replica
    
---